import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from '@/components/SideBar'
import NavBar from '@/components/NavBar'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MoviesForYou',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <NavBar />
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
